# Generated by Django 5.1.6 on 2025-03-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
