# Generated by Django 5.1.6 on 2025-03-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_usuario_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
