# Generated by Django 5.1.6 on 2025-03-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_remove_usuario_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='foto_capa',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='foto_perfil',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
