# Generated by Django 5.1.6 on 2025-03-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_equipe_foto_capa_equipe_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='foto_capa',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
